# Generated by Django 5.1.1 on 2024-10-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BurgerApi', '0002_customerdetails_ingredient_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='cheese',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='meat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='salad',
            field=models.IntegerField(default=0),
        ),
    ]
